import { create, themes } from 'storybook/theming';

export const theme = create({
  ...themes.light,
  base: 'light',
  fontBase: 'IBM Plex Sans, system-ui, sans-serif',
  fontCode: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, monospace',
  colorPrimary: themes.light.colorPrimary,
  colorSecondary: '#59b3b3',
  appBg: '#ffffff',
  appContentBg: '#ffffff',
  appBorderColor: '#ebeaec',
  appBorderRadius: 8,
  appHoverBg: '#f5f5f5',
  appPreviewBg: '#ffffff',
  textColor: '#383641',
  textInverseColor: '#ffffff',
  textMutedColor: '#88868d',
  barTextColor: '#383641',
  barHoverColor: '#f5f5f5',
  barSelectedColor: '#ffb142',
  barBg: '#ffffff',
  buttonBg: '#f5f5f5',
  buttonBorder: '#ebeaec',
  inputBg: '#ffffff',
  inputBorder: '#ebeaec',
  inputTextColor: '#383641',
  inputBorderRadius: 6,
  booleanBg: '#ebeaec',
  booleanSelectedBg: themes.light.booleanSelectedBg,

  brandTitle: 'Landing Challenge',
  brandUrl: '/',
  brandImage: '/logo.png',
});
